name: TODO to Issue

on:
  push:
    branches: [ main, develop ]
  pull_request:
    types: [opened, synchronize]

permissions:
  issues: write
  pull-requests: read

jobs:
  todo-to-issue:
    if: vars.ENABLE_TODO_TO_ISSUE == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Convert TODO to Issue
        uses: alstr/todo-to-issue-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABELS: 'idea'
          PACKAGE_MANAGER: 'auto'
          SKIP_CI: true
